mcip_master_main.obj: ../mcip_master_main.c
mcip_master_main.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/c6x.h
mcip_master_main.obj: D:\Program\Texas\CCSv6.1.2\ccsv6\tools\compiler\ti-cgt-c6000_8.0.3\include\vect.h
mcip_master_main.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stdint.h
mcip_master_main.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stdio.h
mcip_master_main.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/linkage.h
mcip_master_main.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stdarg.h
mcip_master_main.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stdlib.h
mcip_master_main.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/string.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/ndk_2_24_03_35/packages/ti/ndk/inc/netmain.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stacksys.h
mcip_master_main.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stdarg.h
mcip_master_main.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/string.h
mcip_master_main.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stddef.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\usertype.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\socket.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\socketndk.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\serrno.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\os/osif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\hal/hal.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\_nettool.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\nettools/nettools.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\nettools\inc/configif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\nettools\inc/daemonif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\nettools\inc/dhcpif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\nettools\inc/dhcpsif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\nettools\inc/dnsif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\nettools\inc/httpif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\nettools\inc/inet.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\nettools\inc/ipaddrif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\nettools\inc/telnetif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\nettools\inc/tftpif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\nettools\inc/natif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\nettools\inc/dhcpopts.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\nettools\netcfg.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\_netctrl.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\netctrl/netctrl.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\netctrl/netsrv.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/ndk_2_24_03_35/packages/ti/ndk/inc/_stack.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack/stack.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc/listlib.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc/netdf.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc/resif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc/bindif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc/etherif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc/icmpif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc/igmpif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc/ipif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc/lliif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc/natif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc/nodeif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc/rawif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc/routeif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc/rtcif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc/sockif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc\fdtif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc/pipeif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc/tcpif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc/udpif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc/pppoeif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc/pppif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc/vlanif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc/nimuif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc\ip6if.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc/bind6if.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc/route6if.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc/lli6if.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc/icmp6if.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc/mldif.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\ndk_2_24_03_35\packages\ti\ndk\inc\stack\inc/rawethif.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/ndk_2_24_03_35/packages/ti/ndk/inc/tools/console.h
mcip_master_main.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stdlib.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/ndk_2_24_03_35/packages/ti/ndk/inc/tools/servers.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/System.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/std.h
mcip_master_main.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stdarg.h
mcip_master_main.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stddef.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/ti/targets/elf/std.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\xdctools_3_23_04_60\packages\ti\targets\elf\C66.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/ti/targets/std.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/xdc.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types__prologue.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/package/package.defs.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types__epilogue.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/ISystemSupport.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IHeap.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Memory.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IHeap.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Error__prologue.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Main.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IGateProvider.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/package/Main_Module_GateProxy.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IGateProvider.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Error__epilogue.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/package/Memory_HeapProxy.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IHeap.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Assert.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Assert__prologue.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Main.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Diags.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Diags__prologue.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Main.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Diags__epilogue.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Diags.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Assert__epilogue.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IGateProvider.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/package/System_SupportProxy.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/ISystemSupport.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/package/System_Module_GateProxy.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IGateProvider.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/package/System_SupportProxy.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/package/System_Module_GateProxy.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IHeap.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Memory.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/package/Memory_HeapProxy.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/ipc_1_24_03_32/packages/ti/ipc/Ipc.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/ipc_1_24_03_32/packages/ti/ipc/HeapBufMP.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/ipc_1_24_03_32/packages/ti/ipc/GateMP.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/ipc_1_24_03_32/packages/ti/ipc/MultiProc.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/BIOS.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/BIOS__prologue.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/package/package.defs.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IGateProvider.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/package/BIOS_RtsGateProxy.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IGateProvider.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/BIOS__epilogue.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/package/BIOS_RtsGateProxy.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/Task.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/Task__prologue.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/package/package.defs.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/interfaces/ITaskSupport.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/interfaces/package/package.defs.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IHeap.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Assert.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/Clock.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/hal/Timer.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/hal/package/package.defs.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/interfaces/ITimer.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/hal/package/Timer_TimerProxy.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/interfaces/ITimer.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Assert.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/Swi.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Assert.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/Queue.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Diags.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Log.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Log__prologue.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Main.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Diags.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Diags.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Text.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Log__epilogue.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/Queue.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Diags.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Log.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/Queue.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Diags.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Log.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/package/Task_SupportProxy.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/interfaces/ITaskSupport.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/Task__epilogue.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/package/Task_SupportProxy.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/cfg/global.h
mcip_master_main.obj: E:/Studio/TICCS/mcip_master/Debug/configPkg/package/cfg/mcip_master_pe66.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/heaps/HeapMem.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/heaps/package/package.defs.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Memory.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IHeap.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IGateProvider.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Assert.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/heaps/package/HeapMem_Module_GateProxy.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IGateProvider.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/heaps/package/HeapMem_Module_GateProxy.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/platform/platform.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/platform/resource_mgr.h
mcip_master_main.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stdio.h
mcip_master_main.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/string.h
mcip_master_main.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stdlib.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/tistdtypes.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl_chip.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl_types.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl_error.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_chip.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr.h
mcip_master_main.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/c6x.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/soc.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_device.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl_semAux.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl_sem.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_sem.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl_cacheAux.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl_cache.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_cgem.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/cppi/cppi_drv.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_cppidma_global_config.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_cppidma_rx_channel_config.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_cppidma_rx_flow_config.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_cppidma_tx_channel_config.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_cppidma_tx_scheduler_config.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl_cppi.h
mcip_master_main.obj: D:\Program\Texas\MCSDK\pdk_C6678_1_1_2_6\packages\ti\drv\cppi\cppiver.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/cppi/cppi_desc.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/qmss_drv.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/qmssver.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/qmss_qm.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_qm_config.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_qm_descriptor_region_config.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_qm_queue_management.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_qm_queue_status_config.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_pdsp.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_qm_intd.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_mcdma.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_cp_timer16.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl_qm_queue.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/qmss_acc.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/qmss_drv.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/qmss_qos.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/qmss_mgmt.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/include/qmss_pvt.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/qmss_osal.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/pa/pa.h
mcip_master_main.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stdlib.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/pa/paver.h
mcip_master_main.obj: ..\mcip_ipc.h
mcip_master_main.obj: ..\mcip_common.h
mcip_master_main.obj: D:/Program/Texas/MCSDK/ipc_1_24_03_32/packages/ti/ipc/MessageQ.h
