system\platform_osal.obj: ../system/platform_osal.c
system\platform_osal.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stdio.h
system\platform_osal.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/linkage.h
system\platform_osal.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stdarg.h
system\platform_osal.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/string.h
system\platform_osal.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stdlib.h
system\platform_osal.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stdint.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/platform/platform.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/platform/resource_mgr.h
system\platform_osal.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stdio.h
system\platform_osal.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/string.h
system\platform_osal.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stdlib.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/tistdtypes.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/std.h
system\platform_osal.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stdarg.h
system\platform_osal.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stddef.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/ti/targets/elf/std.h
system\platform_osal.obj: D:\Program\Texas\MCSDK\xdctools_3_23_04_60\packages\ti\targets\elf\C66.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/ti/targets/std.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl_chip.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl_types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl_error.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_chip.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr.h
system\platform_osal.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/c6x.h
system\platform_osal.obj: D:\Program\Texas\CCSv6.1.2\ccsv6\tools\compiler\ti-cgt-c6000_8.0.3\include\vect.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/soc.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_device.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl_semAux.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl_sem.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_sem.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl_cacheAux.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl_cache.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_cgem.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/cppi/cppi_drv.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_cppidma_global_config.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_cppidma_rx_channel_config.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_cppidma_rx_flow_config.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_cppidma_tx_channel_config.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_cppidma_tx_scheduler_config.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl_cppi.h
system\platform_osal.obj: D:\Program\Texas\MCSDK\pdk_C6678_1_1_2_6\packages\ti\drv\cppi\cppiver.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/cppi/cppi_desc.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/qmss_drv.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/qmssver.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/qmss_qm.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_qm_config.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_qm_descriptor_region_config.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_qm_queue_management.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_qm_queue_status_config.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_pdsp.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_qm_intd.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_mcdma.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_cp_timer16.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl_qm_queue.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/qmss_acc.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/qmss_drv.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/qmss_qos.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/qmss_mgmt.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/include/qmss_pvt.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/qmss_osal.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/pa/pa.h
system\platform_osal.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stdlib.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/pa/paver.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IHeap.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/xdc.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types__prologue.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/package/package.defs.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types__epilogue.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Memory.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IHeap.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IHeap.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Error__prologue.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Main.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IGateProvider.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/package/Main_Module_GateProxy.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IGateProvider.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Error__epilogue.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/package/Memory_HeapProxy.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IHeap.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/System.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/ISystemSupport.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Assert.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Assert__prologue.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Main.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Diags.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Diags__prologue.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Main.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Diags__epilogue.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Diags.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Assert__epilogue.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IGateProvider.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/package/System_SupportProxy.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/ISystemSupport.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/package/System_Module_GateProxy.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IGateProvider.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/package/System_SupportProxy.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/package/System_Module_GateProxy.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Memory.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/package/Memory_HeapProxy.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/BIOS.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/BIOS__prologue.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/package/package.defs.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IGateProvider.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/package/BIOS_RtsGateProxy.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IGateProvider.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/BIOS__epilogue.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/package/BIOS_RtsGateProxy.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/Task.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/Task__prologue.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/package/package.defs.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/interfaces/ITaskSupport.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/interfaces/package/package.defs.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IHeap.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Assert.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/Clock.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/hal/Timer.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/hal/package/package.defs.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/interfaces/ITimer.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/hal/package/Timer_TimerProxy.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/interfaces/ITimer.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Assert.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/Swi.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Assert.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/Queue.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Diags.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Log.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Log__prologue.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Main.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Diags.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Diags.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Text.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Log__epilogue.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/Queue.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Diags.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Log.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/Queue.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Diags.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Log.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/package/Task_SupportProxy.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/interfaces/ITaskSupport.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/Task__epilogue.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/package/Task_SupportProxy.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/Semaphore.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/Event.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/Event__prologue.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Assert.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/Clock.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/Queue.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/Task.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Diags.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Log.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/Event__epilogue.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Assert.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/Clock.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/Queue.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/Task.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Diags.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Log.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/heaps/HeapBuf.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/heaps/package/package.defs.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Memory.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/knl/Queue.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IHeap.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Assert.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/heaps/HeapMem.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Memory.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IHeap.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IGateProvider.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Assert.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/heaps/package/HeapMem_Module_GateProxy.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/runtime/IGateProvider.h
system\platform_osal.obj: D:/Program/Texas/MCSDK/bios_6_33_06_50/packages/ti/sysbios/heaps/package/HeapMem_Module_GateProxy.h
