system\resourcemgr.obj: ../system/resourcemgr.c
system\resourcemgr.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stdio.h
system\resourcemgr.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/linkage.h
system\resourcemgr.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stdarg.h
system\resourcemgr.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/string.h
system\resourcemgr.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stdlib.h
system\resourcemgr.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stdint.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/platform/resource_mgr.h
system\resourcemgr.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stdio.h
system\resourcemgr.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/string.h
system\resourcemgr.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stdlib.h
system\resourcemgr.obj: D:\Program\Texas\MCSDK\pdk_C6678_1_1_2_6\packages\ti\platform\platform.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/tistdtypes.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/xdc/std.h
system\resourcemgr.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stdarg.h
system\resourcemgr.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stddef.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/ti/targets/elf/std.h
system\resourcemgr.obj: D:\Program\Texas\MCSDK\xdctools_3_23_04_60\packages\ti\targets\elf\C66.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/xdctools_3_23_04_60/packages/ti/targets/std.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl_chip.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl_types.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl_error.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_chip.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr.h
system\resourcemgr.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/c6x.h
system\resourcemgr.obj: D:\Program\Texas\CCSv6.1.2\ccsv6\tools\compiler\ti-cgt-c6000_8.0.3\include\vect.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/soc.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_device.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl_semAux.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl_sem.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_sem.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl_cacheAux.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl_cache.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_cgem.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/cppi/cppi_drv.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_cppidma_global_config.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_cppidma_rx_channel_config.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_cppidma_rx_flow_config.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_cppidma_tx_channel_config.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_cppidma_tx_scheduler_config.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl_cppi.h
system\resourcemgr.obj: D:\Program\Texas\MCSDK\pdk_C6678_1_1_2_6\packages\ti\drv\cppi\cppiver.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/cppi/cppi_desc.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/qmss_drv.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/qmssver.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/qmss_qm.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_qm_config.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_qm_descriptor_region_config.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_qm_queue_management.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_qm_queue_status_config.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_pdsp.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_qm_intd.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_mcdma.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_cp_timer16.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/csl_qm_queue.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/qmss_acc.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/qmss_drv.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/qmss_qos.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/qmss_mgmt.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/include/qmss_pvt.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/qmss_osal.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/pa/pa.h
system\resourcemgr.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stdlib.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/pa/paver.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/csl/cslr_pa_ss.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/qmss_firmware.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/firmware/acc16_le_bin.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/firmware/acc16_be_bin.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/firmware/acc32_le_bin.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/firmware/acc32_be_bin.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/firmware/acc48_le_bin.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/firmware/acc48_be_bin.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/firmware/qos_le_bin.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/firmware/qos_be_bin.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/firmware/qos_sched_le_bin.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/firmware/qos_sched_be_bin.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/pa/fw/classify1_bin.c
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/pa/fw/pafw.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/pa/fw/classify2_bin.c
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/pa/fw/pam_bin.c
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/device/qmss_device.c
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/qmss/qmss_types.h
system\resourcemgr.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stdlib.h
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/cppi/device/cppi_device.c
system\resourcemgr.obj: D:/Program/Texas/MCSDK/pdk_C6678_1_1_2_6/packages/ti/drv/cppi/cppi_types.h
system\resourcemgr.obj: D:/Program/Texas/CCSv6.1.2/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3/include/stdlib.h
